name = "Devito"
uuid = "06ed14b1-0e40-4084-abdf-764a285f8c42"
authors = ["Sam Kaplan <Sam.Kaplan@chevron.com>"]
version = "1.3.2"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"

[weakdeps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
MPIExt = "MPI"

[compat]
MPI = "0.20"
PythonCall = "0.9.30"
Strided = "2"
julia = "1.9"
